"""
Trade Journal Engine.

Provides trade pairing (FIFO matching), P&L attribution (algo vs manual),
multi-day order loading, and aggregation functions for the Trade Journal
dashboard.
"""

import json
import os
import glob
import logging
from datetime import datetime, date, timedelta
from common_lib import get_ist_now
from typing import Optional


# ============================================================================
# Algo Source → Name & Category Mapping
# ============================================================================

ALGO_CATEGORY_MAP: dict = {
    # Survivor (Breakout)
    "Trending_Market_Code": {"algo_name": "Survivor (NIFTY)", "category": "Breakout"},
    "Trend_Mkt_SENSEX": {"algo_name": "Survivor (SENSEX)", "category": "Breakout"},
    "Trend_Mkt_Stock": {"algo_name": "Survivor (Stock)", "category": "Breakout"},
    # Wave Extractor / Scraper (Mean Reversion)
    "Scraper": {"algo_name": "Wave Extractor (Scraper)", "category": "Mean Reversion"},
    # Bulk Order (Manual gap scripts)
    "Gap-Odr_Manual": {"algo_name": "Manual", "category": "Bulk Order"},
    "Gap-Odr_Auto": {"algo_name": "Manual", "category": "Bulk Order"},
    # Unknown / Default
    "Unknown": {"algo_name": "Unknown", "category": "Bulk Order"},
    # Stop Loss
    "SL_Order": {"algo_name": "Stop Loss", "category": "Manual"},
    # UI-placed tagged orders
    "Expiry Day Trade - Yash": {"algo_name": "Expiry Day Trade - Yash", "category": "Expiry Trade"},
}

# Tags that are considered "algo" (non-manual) for attribution purposes
ALGO_TAGS: set = {
    "Trending_Market_Code",
    "Trend_Mkt_SENSEX",
    "Trend_Mkt_Stock",
    "Scraper",
}

# Market condition options
MARKET_CONDITIONS: list = [
    "Trending Up",
    "Trending Down",
    "Ranging",
    "Volatile",
    "Low Volatility",
    "Expiry Day",
]


def classify_source(algo_source: str) -> dict:
    """Classify an algo_source tag into name, category, and type.

    Args:
        algo_source: The algo_source tag from an executed order.

    Returns:
        dict with keys: algo_name, category, is_algo (bool).
    """
    import re
    # Opaque per-order tags generated by place_duo_order(): "S_<unix>_<rand>" / "B_<unix>_<rand>"
    if re.match(r'^[SB]_\d+_\d+$', algo_source or ""):
        return {"algo_name": "Wave Extractor (Scraper)", "category": "Mean Reversion", "is_algo": True}

    info = ALGO_CATEGORY_MAP.get(algo_source, {
        "algo_name": algo_source or "Unknown",
        "category": "Other",
    })
    return {
        "algo_name": info["algo_name"],
        "category": info["category"],
        "is_algo": algo_source in ALGO_TAGS,
    }


# ============================================================================
# Multi-Day Order Loading
# ============================================================================

def _get_status_dir() -> str:
    """Get the path to the status directory containing executed order files.

    Returns:
        str: Absolute path to the status directory.
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(os.path.dirname(base_dir), "status")


def load_orders_for_date(target_date: date) -> list:
    """Load executed orders for a specific date.

    Args:
        target_date: The date to load orders for.

    Returns:
        list: List of order dicts, empty if no file found.
    """
    status_dir = _get_status_dir()
    date_str = target_date.strftime("%Y-%m-%d")
    filepath = os.path.join(status_dir, f"executed_orders_{date_str}.json")

    if not os.path.exists(filepath):
        return []

    try:
        with open(filepath, "r") as f:
            data = json.load(f)
        orders = data.get("orders", [])
        # Add the date to each order for multi-day grouping
        for order in orders:
            order["trade_date"] = date_str
        return orders
    except Exception as e:
        logging.error(f"Error loading orders for {date_str}: {e}")
        return []


def load_orders_range(start_date: date, end_date: date) -> list:
    """Load executed orders across a date range.

    Args:
        start_date: Start date (inclusive).
        end_date: End date (inclusive).

    Returns:
        list: Combined list of orders from all dates, sorted by timestamp.
    """
    all_orders: list = []
    current = start_date

    while current <= end_date:
        orders = load_orders_for_date(current)
        all_orders.extend(orders)
        current += timedelta(days=1)

    # Sort by timestamp ascending for FIFO pairing
    all_orders.sort(key=lambda x: x.get("timestamp", ""))
    return all_orders


def get_available_dates() -> list:
    """Get all dates that have executed order files.

    Returns:
        list: Sorted list of date strings (YYYY-MM-DD).
    """
    status_dir = _get_status_dir()
    pattern = os.path.join(status_dir, "executed_orders_*.json")
    files = glob.glob(pattern)

    dates: list = []
    for f in files:
        basename = os.path.basename(f)
        # Extract date from "executed_orders_YYYY-MM-DD.json"
        date_str = basename.replace("executed_orders_", "").replace(".json", "")
        dates.append(date_str)

    dates.sort()
    return dates


# ============================================================================
# Trade Pairing (FIFO)
# ============================================================================

def pair_trades(orders: list) -> tuple:
    """Pair sell/buy orders into round trips using FIFO matching.

    For each symbol, matches the first sell with the first buy (sell-first)
    or first buy with the first sell (buy-first). Each pair becomes a
    "round trip" with P&L calculated.

    Args:
        orders: List of order dicts sorted by timestamp ascending.

    Returns:
        tuple: (round_trips list, unpaired orders list).
    """
    # Group orders by symbol
    symbol_orders: dict = {}
    for order in orders:
        sym = order.get("symbol", "")
        if sym not in symbol_orders:
            symbol_orders[sym] = {"sells": [], "buys": []}

        if order.get("transaction_type") == "SELL":
            symbol_orders[sym]["sells"].append(order)
        elif order.get("transaction_type") == "BUY":
            symbol_orders[sym]["buys"].append(order)

    round_trips: list = []
    unpaired: list = []

    for sym, data in symbol_orders.items():
        sells = list(data["sells"])  # Copy to avoid mutation
        buys = list(data["buys"])

        # FIFO matching: pair sell with buy in order
        while sells and buys:
            sell = sells[0]
            buy = buys[0]

            sell_time = sell.get("timestamp", "")
            buy_time = buy.get("timestamp", "")

            sell_qty = int(sell.get("quantity", 0))
            buy_qty = int(buy.get("quantity", 0))

            # Determine direction based on which came first
            if sell_time <= buy_time:
                # Sell-first (primary scenario for option selling)
                direction = "sell_first"
                open_trade = sell
                close_trade = buy
            else:
                # Buy-first (rare)
                direction = "buy_first"
                open_trade = buy
                close_trade = sell

            # Match on the minimum quantity
            matched_qty = min(sell_qty, buy_qty)
            sell_price = float(sell.get("price", 0))
            buy_price = float(buy.get("price", 0))

            # P&L: always (sell_price - buy_price) * matched_qty
            pnl = round((sell_price - buy_price) * matched_qty, 2)

            round_trips.append({
                "symbol": sym,
                "direction": direction,
                "open_trade": {
                    "timestamp": open_trade.get("timestamp"),
                    "transaction_type": open_trade.get("transaction_type"),
                    "price": float(open_trade.get("price", 0)),
                    "quantity": matched_qty,
                    "algo_source": open_trade.get("algo_source", "Unknown"),
                    "trade_date": open_trade.get(
                        "trade_date",
                        open_trade.get("timestamp", "")[:10],
                    ),
                    "order_id": open_trade.get("order_id", "") or "",
                },
                "close_trade": {
                    "timestamp": close_trade.get("timestamp"),
                    "transaction_type": close_trade.get("transaction_type"),
                    "price": float(close_trade.get("price", 0)),
                    "quantity": matched_qty,
                    "algo_source": close_trade.get("algo_source", "Unknown"),
                    "trade_date": close_trade.get(
                        "trade_date",
                        close_trade.get("timestamp", "")[:10],
                    ),
                    "order_id": close_trade.get("order_id", "") or "",
                },
                "matched_qty": matched_qty,
                "pnl": pnl,
                "option_type": open_trade.get("option_type", ""),
                "expiry": open_trade.get("expiry", ""),
            })

            # Reduce quantities
            if sell_qty > matched_qty:
                sells[0] = dict(sell)
                sells[0]["quantity"] = sell_qty - matched_qty
            else:
                sells.pop(0)

            if buy_qty > matched_qty:
                buys[0] = dict(buy)
                buys[0]["quantity"] = buy_qty - matched_qty
            else:
                buys.pop(0)

        # Remaining unmatched orders
        for s in sells:
            unpaired.append(s)
        for b in buys:
            unpaired.append(b)

    return round_trips, unpaired


# ============================================================================
# P&L Attribution
# ============================================================================

def attribute_pnl(round_trip: dict) -> dict:
    """Apply P&L attribution rules to a round trip.

    Sell-First Rules:
        - Algo sell → 100% to opening algo (regardless of close)
        - Manual sell + Algo close → 100% to closing algo
        - Manual sell + Manual close → 100% Manual

    Buy-First Rules:
        - Algo buy → 100% to opening algo (regardless of close)
        - Manual buy + Algo close → 50% Algo / 50% Manual
        - Manual buy + Manual close → 100% Manual

    Args:
        round_trip: A round trip dict from pair_trades().

    Returns:
        dict with: algo_pnl, manual_pnl, attribution_label,
                   open_algo_info, close_algo_info.
    """
    pnl = round_trip["pnl"]
    direction = round_trip["direction"]

    open_source = round_trip["open_trade"]["algo_source"]
    close_source = round_trip["close_trade"]["algo_source"]

    open_info = classify_source(open_source)
    close_info = classify_source(close_source)

    open_is_algo = open_info["is_algo"]
    close_is_algo = close_info["is_algo"]

    if direction == "sell_first":
        if open_is_algo:
            # Algo sell → 100% to opening algo
            algo_pnl = pnl
            manual_pnl = 0.0
            label = open_info["algo_name"]
        elif not open_is_algo and close_is_algo:
            # Manual sell + Algo close → 100% to closing algo
            algo_pnl = pnl
            manual_pnl = 0.0
            label = close_info["algo_name"]
        else:
            # Manual sell + Manual close → 100% Manual
            algo_pnl = 0.0
            manual_pnl = pnl
            label = "Manual"
    else:
        # Buy-first
        if open_is_algo:
            # Algo buy → 100% to opening algo
            algo_pnl = pnl
            manual_pnl = 0.0
            label = open_info["algo_name"]
        elif not open_is_algo and close_is_algo:
            # Manual buy + Algo close → 50/50
            algo_pnl = round(pnl * 0.5, 2)
            manual_pnl = round(pnl * 0.5, 2)
            label = f"50% {close_info['algo_name']} / 50% Manual"
        else:
            # Manual buy + Manual close → 100% Manual
            algo_pnl = 0.0
            manual_pnl = pnl
            label = "Manual"

    # Pick category from whichever side determined the attribution
    if open_is_algo:
        category = open_info["category"]
    elif close_is_algo:
        category = close_info["category"]
    else:
        category = "Other"

    return {
        "algo_pnl": algo_pnl,
        "manual_pnl": manual_pnl,
        "attribution_label": label,
        "category": category,
        "open_algo_info": open_info,
        "close_algo_info": close_info,
    }


# ============================================================================
# Journal Summary & Trade Log
# ============================================================================

def get_trade_log(start_date: date, end_date: date) -> dict:
    """Get complete trade log with paired round trips and attribution.

    Serves from the SQLite cache (auto-rebuilt when stale). Callers see
    the same return shape as before; the expensive FIFO pairing only runs
    when new order files are detected or on a daily basis.

    Args:
        start_date: Start date (inclusive).
        end_date: End date (inclusive).

    Returns:
        dict with: round_trips (list, newest first), unpaired (list),
        total_orders (int).
    """
    import trade_journal_db as tjdb  # lazy import to avoid circular dependency

    tjdb.ensure_cache_fresh()
    round_trips = tjdb.query_round_trips(str(start_date), str(end_date))
    unpaired = tjdb.query_unpaired(str(start_date), str(end_date))
    return {
        "round_trips": round_trips,
        "unpaired": unpaired,
        "total_orders": len(round_trips) + len(unpaired),
    }


def get_journal_summary(start_date: date, end_date: date) -> dict:
    """Get aggregated P&L summary by attribution source and category.

    Args:
        start_date: Start date (inclusive).
        end_date: End date (inclusive).

    Returns:
        dict with: total_pnl, algo_pnl, manual_pnl, by_algo, by_category,
                   by_date, win_rate, total_trades, insights.
    """
    trade_log = get_trade_log(start_date, end_date)
    round_trips = trade_log["round_trips"]

    total_pnl = 0.0
    algo_pnl = 0.0
    manual_pnl = 0.0
    wins = 0
    losses = 0
    by_algo: dict = {}
    by_category: dict = {}
    by_date: dict = {}

    best_trade: Optional[dict] = None
    worst_trade: Optional[dict] = None

    for rt in round_trips:
        pnl = rt["pnl"]
        attr = rt["attribution"]

        total_pnl += pnl
        algo_pnl += attr["algo_pnl"]
        manual_pnl += attr["manual_pnl"]

        if pnl >= 0:
            wins += 1
        else:
            losses += 1

        # Track best/worst
        if best_trade is None or pnl > best_trade["pnl"]:
            best_trade = rt
        if worst_trade is None or pnl < worst_trade["pnl"]:
            worst_trade = rt

        # Aggregate by algo name
        label = attr["attribution_label"]
        if label not in by_algo:
            by_algo[label] = {
                "pnl": 0.0,
                "trades": 0,
                "wins": 0,
                "losses": 0,
            }
        by_algo[label]["pnl"] += pnl
        by_algo[label]["trades"] += 1
        if pnl >= 0:
            by_algo[label]["wins"] += 1
        else:
            by_algo[label]["losses"] += 1

        # Aggregate by category
        open_cat = attr["open_algo_info"]["category"]
        if open_cat not in by_category:
            by_category[open_cat] = {"pnl": 0.0, "trades": 0}
        by_category[open_cat]["pnl"] += pnl
        by_category[open_cat]["trades"] += 1

        # Aggregate by date (use open trade date)
        trade_date = rt["open_trade"].get("trade_date", "Unknown")
        if trade_date not in by_date:
            by_date[trade_date] = {"pnl": 0.0, "trades": 0}
        by_date[trade_date]["pnl"] += pnl
        by_date[trade_date]["trades"] += 1

    total_trades = wins + losses
    win_rate = round((wins / total_trades) * 100, 1) if total_trades > 0 else 0

    # Round aggregates
    total_pnl = round(total_pnl, 2)
    algo_pnl = round(algo_pnl, 2)
    manual_pnl = round(manual_pnl, 2)
    for key in by_algo:
        by_algo[key]["pnl"] = round(by_algo[key]["pnl"], 2)
    for key in by_category:
        by_category[key]["pnl"] = round(by_category[key]["pnl"], 2)
    for key in by_date:
        by_date[key]["pnl"] = round(by_date[key]["pnl"], 2)

    # Calculate cumulative P&L by date (sorted)
    sorted_dates = sorted(by_date.keys())
    cumulative_pnl: list = []
    running = 0.0
    for d in sorted_dates:
        running += by_date[d]["pnl"]
        cumulative_pnl.append({
            "date": d,
            "daily_pnl": by_date[d]["pnl"],
            "cumulative_pnl": round(running, 2),
            "trades": by_date[d]["trades"],
        })

    return {
        "total_pnl": total_pnl,
        "algo_pnl": algo_pnl,
        "manual_pnl": manual_pnl,
        "total_trades": total_trades,
        "wins": wins,
        "losses": losses,
        "win_rate": win_rate,
        "by_algo": by_algo,
        "by_category": by_category,
        "cumulative_pnl": cumulative_pnl,
        "unpaired_count": len(trade_log["unpaired"]),
        "insights": {
            "best_trade": {
                "symbol": best_trade["symbol"],
                "pnl": best_trade["pnl"],
                "date": best_trade["open_trade"].get("trade_date", ""),
            } if best_trade else None,
            "worst_trade": {
                "symbol": worst_trade["symbol"],
                "pnl": worst_trade["pnl"],
                "date": worst_trade["open_trade"].get("trade_date", ""),
            } if worst_trade else None,
        },
    }


# ============================================================================
# Trade Notes Persistence
# ============================================================================

def _get_notes_filepath() -> str:
    """Get filepath for trade notes JSON.

    Returns:
        str: Absolute path to trade_notes.json.
    """
    status_dir = _get_status_dir()
    return os.path.join(status_dir, "trade_notes.json")


def _load_notes() -> dict:
    """Load all trade notes.

    Returns:
        dict: Mapping of note_key → note data.
    """
    filepath = _get_notes_filepath()
    if not os.path.exists(filepath):
        return {}
    try:
        with open(filepath, "r") as f:
            return json.load(f)
    except Exception as e:
        logging.error(f"Error loading trade notes: {e}")
        return {}


def save_trade_note(
    symbol: str,
    trade_date: str,
    note_text: str,
    market_condition: str = "",
    lesson: str = "",
) -> bool:
    """Save a note for a specific trade.

    Args:
        symbol: Trading symbol of the trade.
        trade_date: Date of the trade (YYYY-MM-DD).
        note_text: Free-text note.
        market_condition: Market condition tag.
        lesson: Lesson learned from this trade.

    Returns:
        bool: True if saved successfully.
    """
    try:
        notes = _load_notes()
        key = f"{trade_date}_{symbol}"
        notes[key] = {
            "symbol": symbol,
            "trade_date": trade_date,
            "note": note_text,
            "market_condition": market_condition,
            "lesson": lesson,
            "updated_at": get_ist_now().isoformat(),
        }

        filepath = _get_notes_filepath()
        with open(filepath, "w") as f:
            json.dump(notes, f, indent=2)

        return True
    except Exception as e:
        logging.error(f"Error saving trade note: {e}")
        return False


def get_trade_notes() -> dict:
    """Get all trade notes.

    Returns:
        dict: All notes keyed by date_symbol.
    """
    return _load_notes()


# ============================================================================
# Zerodha Reconciliation (for manual trades placed outside the system)
# ============================================================================

def reconcile_with_zerodha(kite_client, target_date: date) -> dict:
    """Fetch kite.trades() and insert any fills missing from the local JSON.

    Zerodha's trade API only covers the current session, so this function is
    only effective for today's date. Trades already present are identified by
    ``order_id`` (exact) or by ``symbol + transaction_type + quantity`` (fallback
    for records written before the order_id field was added).

    Partial fills from CANCELLED or REJECTED orders are skipped — they are not
    complete executions and would leave unmatched legs in the journal.

    Missing trades are saved with ``algo_source="Manual"`` since they were placed
    directly on Zerodha outside the trading system.

    Args:
        kite_client: An authenticated KiteConnect instance.
        target_date: The date to reconcile (should be today).

    Returns:
        dict with keys:
            added (int): Number of trades added.
            skipped (int): Number of trades already present.
            partial_skipped (int): Partial fills from cancelled/rejected orders skipped.
            errors (list[str]): Descriptions of any per-trade errors.
    """
    added = 0
    skipped = 0
    partial_skipped = 0
    errors: list = []

    try:
        zerodha_trades = kite_client.trades()
    except Exception as exc:
        logging.error("reconcile_with_zerodha: kite.trades() failed: %s", exc)
        return {"added": 0, "skipped": 0, "partial_skipped": 0, "errors": [str(exc)]}

    # Fetch order metadata to detect partial fills from cancelled/rejected orders.
    # A fill from kite.trades() may be a partial fill if its parent order was
    # subsequently cancelled — these create phantom open legs in the journal.
    try:
        zerodha_orders = kite_client.orders()
        order_status_map: dict[str, dict] = {
            str(o.get("order_id", "")): o for o in zerodha_orders
        }
    except Exception as exc:
        logging.warning(
            "reconcile_with_zerodha: kite.orders() failed, partial-fill filtering disabled: %s",
            exc,
        )
        order_status_map = {}

    existing_orders = load_orders_for_date(target_date)

    # Build two lookup sets for dedup: by order_id and by (symbol, type, qty)
    existing_order_ids: set[str] = {
        str(o["order_id"]) for o in existing_orders if o.get("order_id")
    }
    existing_fuzzy_keys: set = {
        (o["symbol"], o["transaction_type"], int(o.get("quantity", 0)))
        for o in existing_orders
    }

    for trade in zerodha_trades:
        trade_order_id = str(trade.get("order_id", ""))
        symbol = trade.get("tradingsymbol", "")
        transaction_type = trade.get("transaction_type", "")
        quantity = int(trade.get("quantity", 0) or trade.get("filled_quantity", 0))
        fill_price = float(trade.get("average_price", 0) or trade.get("price", 0))

        if not symbol or not transaction_type or quantity <= 0:
            continue

        # Only journal F&O trades (NFO = NSE F&O, BFO = BSE F&O).
        # Equity/ETF trades on NSE/BSE are out of scope for the trade journal.
        trade_exchange = trade.get("exchange", "")
        if trade_exchange not in ("NFO", "BFO"):
            logging.debug(
                "reconcile_with_zerodha: skipping non-FNO trade %s on exchange=%s",
                symbol, trade_exchange,
            )
            continue

        # Skip partial fills from cancelled or rejected orders.
        # kite.trades() returns fill events even when the parent order was later
        # cancelled after partial execution — the unfilled remainder means the
        # position is not what it appears, leaving a phantom open leg in the journal.
        if trade_order_id and order_status_map:
            order_info = order_status_map.get(trade_order_id, {})
            order_final_status = order_info.get("status", "")
            if order_final_status in ("CANCELLED", "REJECTED"):
                order_total_qty = int(order_info.get("quantity", 0))
                order_filled_qty = int(order_info.get("filled_quantity", 0))
                if order_total_qty > 0 and order_filled_qty < order_total_qty:
                    logging.info(
                        "reconcile_with_zerodha: skipping partial fill "
                        "order_id=%s %s %s x%s (status=%s filled=%s/%s)",
                        trade_order_id, symbol, transaction_type, quantity,
                        order_final_status, order_filled_qty, order_total_qty,
                    )
                    partial_skipped += 1
                    continue

        # Exact dedup by order_id (preferred; covers all modern Zerodha trades)
        if trade_order_id and trade_order_id in existing_order_ids:
            skipped += 1
            continue

        # Fuzzy dedup: backward-compat ONLY for trades with no order_id.
        # Two different orders can legitimately share the same (symbol, type, qty)
        # on the same day, so we must never apply this check when order_id is present.
        if not trade_order_id:
            fuzzy_key = (symbol, transaction_type, quantity)
            if fuzzy_key in existing_fuzzy_keys:
                skipped += 1
                continue

        # Determine fill timestamp; fall back to IST now
        fill_ts = trade.get("fill_timestamp") or trade.get("order_timestamp")
        if fill_ts and not isinstance(fill_ts, str):
            fill_ts = fill_ts.isoformat()
        if not fill_ts:
            from common_lib import get_ist_now
            fill_ts = get_ist_now().isoformat()

        try:
            from common_lib import save_executed_order
            saved = save_executed_order(
                symbol=symbol,
                transaction_type=transaction_type,
                price=fill_price,
                quantity=quantity,
                algo_source="Manual",
                order_id=trade_order_id,
            )
            if saved:
                added += 1
                existing_order_ids.add(trade_order_id)
                # Do NOT update existing_fuzzy_keys here — order_id is the
                # dedup gate for modern trades.  Updating the fuzzy set would
                # incorrectly block a second legitimate order of the same
                # symbol/side/qty (but different order_id) later in this loop.
                logging.info(
                    "reconcile_with_zerodha: added missing trade %s %s %s x%s",
                    trade_order_id, symbol, transaction_type, quantity,
                )
            else:
                errors.append(f"save failed for order_id={trade_order_id} {symbol}")
        except Exception as exc:
            error_msg = f"error saving order_id={trade_order_id} {symbol}: {exc}"
            logging.error("reconcile_with_zerodha: %s", error_msg)
            errors.append(error_msg)

    logging.info(
        "reconcile_with_zerodha: date=%s added=%d skipped=%d partial_skipped=%d errors=%d",
        target_date, added, skipped, partial_skipped, len(errors),
    )
    return {"added": added, "skipped": skipped, "partial_skipped": partial_skipped, "errors": errors}


# ============================================================================
# Position Validation
# ============================================================================

def validate_positions_vs_zerodha(kite_client, target_date: date) -> dict:
    """Compare trade journal implied open positions against Zerodha actual positions.

    Runs after EOD reconcile to detect mismatches: positions Zerodha shows that
    have no open leg in the journal (data gaps), and orphan open legs in the
    journal that Zerodha shows as flat (phantom orders).

    Args:
        kite_client: An authenticated KiteConnect instance.
        target_date: The date being validated (used for report filename).

    Returns:
        dict with keys:
            validated_at (str): ISO timestamp of validation run.
            matched (list): Symbols where journal and Zerodha agree.
            discrepancies (list): Symbols where Zerodha shows a position the
                journal lacks an open leg for. Each entry has:
                symbol, zerodha_qty, journal_qty, zerodha_avg_price,
                suggested_transaction_type, suggested_trade_date.
            phantoms (list): Symbols with a journal open leg but Zerodha qty=0.
                Each entry has: symbol, journal_qty, transaction_type.
    """
    validated_at = get_ist_now().isoformat()
    matched: list = []
    discrepancies: list = []
    phantoms: list = []

    # Fetch Zerodha net positions
    try:
        positions_data = kite_client.positions()
        net_positions = positions_data.get("net", [])
    except Exception as exc:
        logging.error("validate_positions_vs_zerodha: kite.positions() failed: %s", exc)
        return {
            "validated_at": validated_at,
            "error": str(exc),
            "matched": [],
            "discrepancies": [],
            "phantoms": [],
        }

    # Build Zerodha position map: symbol → {qty, avg_price}
    zerodha_map: dict[str, dict] = {}
    for pos in net_positions:
        sym = pos.get("tradingsymbol", "")
        qty = int(pos.get("quantity", 0))
        avg_price = float(pos.get("average_price", 0))
        if sym and qty != 0:
            zerodha_map[sym] = {"qty": qty, "avg_price": avg_price}

    # Build journal implied open positions from unpaired orders across all dates
    import trade_journal_db as tjdb
    tjdb.ensure_cache_fresh()
    unpaired_rows = tjdb.query_unpaired_all()  # returns list of unpaired order dicts

    # Aggregate unpaired by symbol: positive = net long (more buys), negative = net short
    journal_map: dict[str, dict] = {}
    for order in unpaired_rows:
        sym = order.get("symbol", "")
        qty = int(order.get("quantity", 0))
        txn = order.get("transaction_type", "")
        if not sym:
            continue
        if sym not in journal_map:
            journal_map[sym] = {"qty": 0, "orders": []}
        delta = qty if txn == "BUY" else -qty
        journal_map[sym]["qty"] += delta
        journal_map[sym]["orders"].append(order)

    # Compare Zerodha positions against journal
    all_symbols = set(zerodha_map) | set(journal_map)
    for sym in all_symbols:
        z_qty = zerodha_map.get(sym, {}).get("qty", 0)
        j_qty = journal_map.get(sym, {}).get("qty", 0)
        z_avg = zerodha_map.get(sym, {}).get("avg_price", 0.0)

        if z_qty == j_qty:
            if z_qty != 0:
                matched.append({"symbol": sym, "qty": z_qty})
        elif z_qty != 0 and j_qty == 0:
            # Zerodha has position; journal has no open leg → data gap
            # Suggest carry-forward: inject the OPPOSITE of the current position
            # (Zerodha -325 means a short was opened — inject a SELL)
            suggested_txn = "SELL" if z_qty < 0 else "BUY"
            discrepancies.append({
                "symbol": sym,
                "zerodha_qty": z_qty,
                "journal_qty": j_qty,
                "zerodha_avg_price": z_avg,
                "suggested_transaction_type": suggested_txn,
                "suggested_quantity": abs(z_qty),
                "suggested_trade_date": (target_date - timedelta(days=1)).isoformat(),
            })
        elif z_qty == 0 and j_qty != 0:
            # Journal has open leg; Zerodha is flat → phantom order in journal
            txn_type = "BUY" if j_qty > 0 else "SELL"
            phantoms.append({
                "symbol": sym,
                "journal_qty": j_qty,
                "transaction_type": txn_type,
                "orders": journal_map[sym]["orders"],
            })
        else:
            # Both non-zero but differ in magnitude
            suggested_txn = "SELL" if z_qty < 0 else "BUY"
            discrepancies.append({
                "symbol": sym,
                "zerodha_qty": z_qty,
                "journal_qty": j_qty,
                "zerodha_avg_price": z_avg,
                "suggested_transaction_type": suggested_txn,
                "suggested_quantity": abs(z_qty - j_qty),
                "suggested_trade_date": (target_date - timedelta(days=1)).isoformat(),
            })

    report = {
        "validated_at": validated_at,
        "matched": matched,
        "discrepancies": discrepancies,
        "phantoms": phantoms,
    }

    # Persist report so the API can serve it without re-running
    try:
        status_dir = _get_status_dir()
        report_path = os.path.join(
            status_dir, f"position_validation_{target_date.isoformat()}.json"
        )
        with open(report_path, "w") as f:
            json.dump(report, f, indent=2)
        logging.info("validate_positions_vs_zerodha: report saved to %s", report_path)
    except Exception as exc:
        logging.error("validate_positions_vs_zerodha: failed to save report: %s", exc)

    logging.info(
        "validate_positions_vs_zerodha: date=%s matched=%d discrepancies=%d phantoms=%d",
        target_date, len(matched), len(discrepancies), len(phantoms),
    )
    return report


# ============================================================================
# Carry-Forward Injection
# ============================================================================

def inject_carry_forward(
    symbol: str,
    transaction_type: str,
    price: float,
    quantity: int,
    trade_date: date,
    note: str = "",
) -> dict:
    """Inject a synthetic open-leg order to represent a position opened on a prior day.

    Used to fix data gaps where the opening trade was not recorded locally
    (e.g. position opened before local tracking started, or placed manually
    before reconcile was running).

    The synthetic order is tagged algo_source="Carry Forward" and timestamped
    at 09:15:00 IST on trade_date so it sorts before any same-day closes.

    Args:
        symbol: Trading symbol (e.g. 'NIFTY2651223950PE').
        transaction_type: 'BUY' or 'SELL' — the direction of the opening leg.
        price: Average fill price to use for P&L calculation.
        quantity: Number of units.
        trade_date: The date to inject the order into (usually yesterday).
        note: Optional human-readable reason stored in the order.

    Returns:
        dict with keys: success (bool), order (dict), message (str).

    Raises:
        ValueError: If transaction_type is invalid or quantity <= 0.
    """
    if transaction_type not in ("BUY", "SELL"):
        raise ValueError(f"transaction_type must be BUY or SELL, got {transaction_type!r}")
    if quantity <= 0:
        raise ValueError(f"quantity must be positive, got {quantity}")
    if price < 0:
        raise ValueError(f"price must be non-negative, got {price}")

    from common_lib import save_executed_order
    from zoneinfo import ZoneInfo

    IST = ZoneInfo("Asia/Kolkata")
    synthetic_ts = datetime(
        trade_date.year, trade_date.month, trade_date.day,
        9, 15, 0, tzinfo=IST,
    ).isoformat()

    # Build the order dict manually so we can control the timestamp
    status_dir = _get_status_dir()
    date_str = trade_date.strftime("%Y-%m-%d")
    filepath = os.path.join(status_dir, f"executed_orders_{date_str}.json")

    symbol_info = _extract_symbol_info(symbol)
    order: dict = {
        "timestamp": synthetic_ts,
        "symbol": symbol,
        "expiry": symbol_info.get("expiry", ""),
        "option_type": symbol_info.get("option_type", ""),
        "transaction_type": transaction_type,
        "price": float(price),
        "quantity": int(quantity),
        "instrument_token": "",
        "segment": "",
        "algo_source": "Carry Forward",
        "order_id": "",
    }
    if note:
        order["note"] = note

    try:
        if os.path.exists(filepath):
            with open(filepath, "r") as f:
                data = json.load(f)
        else:
            data = {"orders": []}

        data["orders"].append(order)

        with open(filepath, "w") as f:
            json.dump(data, f, indent=2)

        logging.info(
            "inject_carry_forward: injected %s %s x%s @ %.2f into %s",
            transaction_type, symbol, quantity, price, date_str,
        )
        return {"success": True, "order": order, "message": f"Injected into {date_str}"}
    except Exception as exc:
        logging.error("inject_carry_forward: failed: %s", exc)
        return {"success": False, "order": order, "message": str(exc)}


def _extract_symbol_info(symbol: str) -> dict:
    """Extract expiry and option_type from a trading symbol string.

    Args:
        symbol: Trading symbol (e.g. 'NIFTY2651223950PE').

    Returns:
        dict with keys: expiry (str), option_type (str).
    """
    import re
    option_type = "OTHER"
    expiry = "UNKNOWN"
    match = re.search(r"(\d{5,6})(CE|PE|FUT)$", symbol)
    if match:
        expiry = match.group(1)
        option_type = match.group(2)
    return {"expiry": expiry, "option_type": option_type}
